let tabs = {
  id: "granite-block",
  options: {
    g_style: "step",
    g_align_tabs: "center",
    g_font_size: "30px",
    g_font_color: "",
    g_font_hover_color: "",
    g_icon_size: "",
    g_step_number_color: "",
    g_title_size: "20px",
    g_title_color: "",
    g_description_size: "12px",
    g_description_color: "",
    g_highlight_color: "",
    g_background_color: "",
    g_background_active_color: "",
    g_background_hover_color: "",
    g_align: "center",
    g_align_icon: false,
    g_direction: "row",
    g_padding: "10px 40px",
    g_margin: "0",
    g_border_width: "",
    g_border_color: "red",
    g_border_radius: "",
    g_full_width: true,
    g_action_header: "",
    g_action_header_size: "28px",
    g_action_header_color: "#5d5d5d",
    g_action_header_bottom_margin: "20px",
    g_action_description: "",
    g_action_description_size: "18px",
    g_action_description_color: "#5d5d5d",
    g_action_description_bottom_margin: "20px",
    g_action_align_text: "left",
    g_action_bottom_margin: "25px",
    g_action_border: true,
    g_classes: "",
    g_cursor_disabled: false,
    g_action: "hash_builder",
  },
  records: [
    {
      name: "Builder",
      desc: "Suspendisse eget felis nec enim",
      icon: "fab fa-angellist",
      href: "/?username=jason&tab=1",
    },
    {
      name: "Settings",
      desc: "Nulla maximus",
      disabled: false,
      href: "?tab=2",
    },
    {
      name: "Account",
      desc: "",
      href: "?tab=3",
    },
    {
      name: "This is a long name",
      desc: "Lorem ipsum dolor sit amet",
      href: "?tab=4",
    },
    {
      name: "Builder",
      desc: "Suspendisse eget felis nec enim",
      icon: "fab fa-angellist",
      href: "/?username=jason&tab=5",
    },
    {
      name: "Settings",
      desc: "Nulla maximus",
      href: "?tab=6",
    },
    {
      name: "Account",
      desc: "",
      href: "?tab=7",
    },
    {
      name: "This is a long name",
      desc: "Lorem ipsum dolor sit amet",
      href: "?tab=8",
    },
  ],
};
